### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by kmuralidharan91** [rzmn/CropView#13]
![image](https://user-images.githubusercontent.com/7802406/65756578-f9f97380-e132-11e9-85a5-817f61317ad6.png)

Xcode 11
Swift 5

**Comment by mcnels** [comment]
Break the expression into multiple statements. For example:
```
let xVal = -cropViewOrigin.x + imageViewOrigin.x + imageOrigin.x + SECropView.cornerSize / 2.0
let yVal = -cropViewOrigin.y + imageViewOrigin.y + imageOrigin.y + SECropView.cornerSize / 2.0

let shift = CGPoint(x: xVal, y: yVal)
```

**Comment by kmuralidharan91** [comment]
yeah, thanks @mcnels, I did the same in the code, actually, it will be great if you have this changes in the repo.
(every time when I run pod, it keeps failing and expecting me to break it again)

**Comment by kmuralidharan91** [comment]
https://github.com/kmuralidharan91/CropView/commit/10ad05b7ecc22efdc2f9f318098bfc055d3f636b
