### ISSUE TITLE
Adding  a navigation and toolbar element in controller

### ISSUE THREAD

**Issue by ghost** [rzmn/CropView#4]
Hi,
I added a navigation bar and toolbar(on bottom), tried to add via storyboard the CropView, but seems the coordinates and CropView and uiimageView frame are incorrect. Could you please implement a solution to fix this error, please?

Regards,
Rony

**Comment by ghost** [comment]
Also, could you please provide your email to text you via?

Regards

**Comment by rzmn** [comment]
Added email to profile information
