### ISSUE TITLE
Set crop corners when image is rotated.

### ISSUE THREAD

**Issue by yajra** [rzmn/CropView#7]
Hi, is there a way to reconfigure crop corners when the image is rotated? Something like below:

```swift
    @IBAction func rotatePressed(_ sender: Any) {
        let degress = CGFloat.pi / 2
        self.imagePreview.transform = imagePreview.transform.rotated(by: degress)
        let rotatedImage = imagePreview.image!
        cropView.setCorners(newCorners: [
            CGPoint(x: 0, y: 0),
            CGPoint(x: rotatedImage.size.width, y: 0),
            CGPoint(x: rotatedImage.size.width, y: rotatedImage.size.height),
            CGPoint(x: 0, y: rotatedImage.size.height)
        ])
    }
```

Rotation work here but the crop area is not centered on the image. TIA.

**Comment by fukemy** [comment]
I think u can using Math, just get a center point in center image (called centerP).
 you will have centerP + currentP (that current point in screen)
 assume the rotation is 30 degree. Let assume desP is the new point when rotate. We have a tritancle
 
 
          currentP - centerP - desP

The math say the space from currentP ->  centerP is equal to desP -> centerP. So u can using Math to calculate the desP.
